export const phases = [
  { name: "Understand", detail: "Discover + Assess", route: "/assess", topic: "evidence", copy: "See what you have and what needs attention." },
  { name: "Prepare", detail: "Plan + Map & Approve", route: "/plan-map-approve", topic: "mappings", copy: "Review the plan. You approve key decisions." },
  { name: "Move", detail: "Migrate + Resolve", route: "/migrate-resolve", topic: "recovery", copy: "Move in safe steps. Resolve blockers before moving forward." },
  { name: "Verify", detail: "Validate + Configure", route: "/validate-configure", topic: "reconciliation", copy: "We verify your numbers and review your setup." },
  { name: "Start", detail: "Onboard + First Real Task", route: "/onboard-fpu", topic: "business-ready", copy: "Complete and verify your first productive task." },
] as const;
export const topics = [
  { id: "why-migrate", title: "Why businesses migrate", body: "Growth, collaboration and connected workflows can outgrow the current accounting setup. A move should solve an operating problem, not simply replace software.", question: "What will your team be able to do afterward?", phase: 0 },
  { id: "what-moves", title: "What gets migrated", body: "Accounts, customers, suppliers, products and transactions are only part of the picture. History, tax, settings, access and integrations need explicit scope too. Unsupported items must be visible, never silently dropped.", question: "What is included, excluded or blocked?", phase: 0 },
  { id: "mappings", title: "Why mappings matter", body: "A mapping connects a source concept to its intended destination. Similar names do not guarantee the same accounting meaning. Review evidence and compatible alternatives before approving.", question: "Does this destination preserve the meaning of the source?", phase: 1 },
  { id: "reconciliation", title: "What reconciliation means", body: "Moving a record is not proof that it moved correctly. Rules compare counts, references and balances against source evidence. A mismatch blocks progress; approval cannot turn a failed check into a pass.", question: "Which check passed, and which evidence supports it?", phase: 3 },
  { id: "approvals", title: "Why some decisions require approval", body: "Decisions affecting accounting treatment, access or business operations need an accountable person. You may approve, reject or stop. An agent cannot approve its own consequential proposal.", question: "What changes, what is the risk, and can it be reversed?", phase: 1 },
  { id: "confidence", title: "What confidence means", body: "Confidence expresses uncertainty in a recommendation. It is not a guarantee or permission to act. The current Beta uses versioned policy-based suggestions, not a live model's calibrated predictions.", question: "What uncertainty remains, even if confidence looks high?", phase: 1 },
  { id: "evidence", title: "What evidence means", body: "Evidence connects a finding to source facts, a rule result or an attributable decision. Explanations help you understand the evidence; they cannot replace it.", question: "Can I trace this recommendation to a fact or check?", phase: 0 },
  { id: "financial-truth", title: "Why financial truth is deterministic", body: "The same inputs and versioned rules must produce the same accounting result. Models may explain or suggest; exact calculations, reconciliation and approval controls decide whether work can proceed.", question: "Is this a suggestion or a verified result?", phase: 3 },
  { id: "recovery", title: "What happens when migration fails", body: "Work pauses at a safe boundary, preserving completed checkpoints and failure evidence. Review the proposed remedy. Consequential recovery needs your approval; retry only when the workflow permits it.", question: "What completed, what failed, and what will retry do?", phase: 2 },
  { id: "business-ready", title: "What Business Ready · Verified means", body: "Required data, setup, access and onboarding checks pass, then an authorized user completes an agreed task with verified evidence. In this Beta that is a synthetic invoice—not proof of production readiness. The formal outcome is Verified First Productive Use.", question: "Has the productive task been verified, not merely posted?", phase: 4 },
] as const;
export const publicLinks = [["Product", "/product"], ["Guide", "/guide"], ["Simulator", "/simulator"], ["Learn", "/learn"], ["Play", "/play"], ["Trust", "/trust"], ["Feedback", "/feedback"], ["Support", "/support"]] as const;
export const sampleEntry = "/assess?sample=harbor-light-migrate-demo";
export const scope = "Synthetic Data · Public Reference · Beta. No live provider migration or production readiness claim.";
