"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import { Alert, Button, Card, StatusBadge } from "@/components/ui";
import { Surface } from "./Surface";
const steps = [
  { title: "Review a mapping", evidence: "The source account is Accounts Receivable, an asset. The suggested destination is also Accounts Receivable. Similar names alone are not enough.", good: "Check account meaning, then approve", bad: "Approve from the name alone", consequence: "Names can hide incompatible accounting treatment. Inspect the account evidence before deciding.", success: "You reviewed compatible account meaning before approving. In the product, the server records who approved and checks the mapping." },
  { title: "Resolve a blocker", evidence: "Two customer records share a name but have different source IDs. Migration paused; the completed account checkpoint is safe.", good: "Review evidence and approve a bounded remedy", bad: "Merge silently and retry everything", consequence: "A name match does not authorize a merge. Replaying completed work risks duplicate writes. The governed workflow stays paused.", success: "A scoped human decision permits the remedy. Retry resumes from the failed batch and preserves completed work." },
  { title: "Verify the outcome", evidence: "The record count matches, but a balance check reports a difference. File transfer completed; financial verification did not.", good: "Stop, investigate and revalidate", bad: "Declare success because records arrived", consequence: "Matching counts cannot prove financial correctness. A failed balance check blocks progress, even after approval.", success: "The mismatch must be repaired and checks rerun. Only then can setup, onboarding and verified first productive use follow." },
];
export function Play() {
  const [step, setStep] = useState(-1);
  const [result, setResult] = useState<"good" | "bad" | null>(null);
  const heading = useRef<HTMLHeadingElement>(null);
  function advance(next: number) { setStep(next); setResult(null); requestAnimationFrame(() => heading.current?.focus()); }
  const current = steps[step];
  return <Surface eyebrow="Play" title="Small choices. Meaningful consequences." intro="An educational synthetic exercise, not a migration or an assessment. Three decisions teach evidence, approvals and recovery. Nothing here reads or changes your workspace."><section className="panel p-6 sm:p-8"><h2 ref={heading} tabIndex={-1} className="type-section">{step === -1 ? "Choose your exercise" : current ? `Decision ${step + 1} of 3: ${current.title}` : "Learning exercise complete"}</h2>{step === -1 ? <Card className="mt-6"><h3 className="type-card">Harbor Light: a safer move</h3><p className="mt-3 text-secondary">Review an account mapping, face a duplicate-customer blocker, then interpret a reconciliation result.</p><Button className="mt-5" onClick={() => advance(0)}>Start learning scenario</Button></Card> : current ? <><p className="mt-5 leading-7 text-secondary">Evidence: {current.evidence}</p><div className="mt-6 flex flex-wrap gap-3"><Button variant="secondary" onClick={() => setResult("good")}>{current.good}</Button><Button variant="secondary" onClick={() => setResult("bad")}>{current.bad}</Button></div>{result && <div className="mt-6"><Alert tone={result === "good" ? "success" : "warning"} title={result === "good" ? "Governed choice" : "Unsafe shortcut — try again"}><p>{result === "good" ? current.success : current.consequence}</p></Alert></div>}{result === "good" && <Button className="mt-6" onClick={() => advance(step + 1)}>Continue lesson</Button>}</> : <><div className="mt-5"><StatusBadge status="COMPLETED"/></div><p className="mt-4 leading-7">You practiced three decisions. This is not migration completion, verified financial evidence or Business Ready status.</p><Link className="button mt-6" href="/simulator">Try the real synthetic workflow</Link></>}{step >= 0 && <Button variant="ghost" className="mt-6" onClick={() => advance(-1)}>Restart exercise</Button>}</section><Link className="button secondary" href="/learn#financial-truth">Learn why financial truth needs rules</Link></Surface>;
}
