"use client";
import Link from "next/link";
import { Alert, Button, Card } from "@/components/ui";
import { Surface } from "./Surface";
import { phases, sampleEntry } from "./content";
import { useSessionView } from "./session";
export function ProductEntry() {
  const { view, loading, error, refresh } = useSessionView();
  return <Surface sourceScope="Sample or user-provided source · synthetic target" eyebrow="Product" title="Your next move starts with understanding." intro="Explore the working Beta with a sample business, or rehearse the same journey in Simulator. Your approvals and verified evidence—not these entry pages—control progress."><div className="grid gap-5 md:grid-cols-2"><Card><h2 className="type-section">Explore Sample Business</h2><p className="mt-3 leading-7 text-secondary">Start Harbor Light Books at Discover + Assess. No mappings, approvals or financial writes are created until you take the relevant steps.</p><Link className="button mt-6" href={sampleEntry}>Explore Sample Business</Link><p className="mt-3 text-sm text-muted">Creates a new session only when you start discovery.</p></Card><Card><h2 className="type-section">Practice with context</h2><p className="mt-3 leading-7 text-secondary">See the scenario, decisions and success criteria before opening the same canonical workflow.</p><Link className="button secondary mt-6" href="/simulator">Open Simulator</Link></Card></div>
    <section><h2 className="type-section">How would you like to experience MoveBooks AI?</h2><Card className="mt-4"><h3 className="type-card">Try Your Data</h3><p className="mt-3">Validate a controlled, de-identified accounting package before entering the same governed journey. Local Beta only; all target operations remain synthetic.</p><Link className="button mt-4" href="/try-your-data">Try Your Data</Link></Card></section><section aria-label="Current local session"><h2 className="type-section">Continue your workspace</h2>{loading ? <p role="status" className="mt-4">Reading local session reference…</p> : error ? <Alert tone="warning" title="Session unavailable"><p>{error}</p></Alert> : view ? <div className="card mt-4 p-5"><p className="break-words">{phases[view.phase].name} · {view.status.replaceAll("_", " ")}</p><Link className="button mt-4" href={`${phases[view.phase].route}?session=${view.id}`}>Continue current session</Link><Link className="button secondary mt-4 ml-2" href={`/trust?session=${view.id}`}>Inspect evidence</Link></div> : <p className="mt-4 text-secondary">No session selected. Explore a sample to begin; we do not create one automatically.</p>}<Button variant="ghost" className="mt-3" onClick={refresh} disabled={loading}>Refresh session reference</Button></section>
    <section><h2 className="type-section">Your five-phase guide</h2><ol className="mt-5 grid gap-4 md:grid-cols-5">{phases.map(phase => <li id={phase.name.toLowerCase()} key={phase.name} className="card scroll-mt-8 p-5"><h3 className="font-bold">{phase.name}</h3><p className="mt-2 text-sm text-secondary">{phase.detail}</p><p className="mt-3 text-sm">{phase.copy}</p><Link className="mt-4 inline-block font-semibold text-primary underline" href={`/learn#${phase.topic}`}>Learn about {phase.name}</Link></li>)}</ol></section><p className="text-sm text-muted">Local demo access only. Production identity and durable sessions are not available. A server restart expires synthetic work; do not use real business data.</p></Surface>;
}
