"use client";
import Link from "next/link";
import { Alert, Button, Card } from "@/components/ui";
import { Surface } from "./Surface";
import { phases, sampleEntry } from "./content";
import { useSessionView } from "./session";
export function ProductEntry() {
  const { view, loading, error, refresh } = useSessionView();
  return <Surface sourceScope="MoveBooks AI Beta" scopeNote="Bounded synthetic Beta · No production customer data" eyebrow="Product" title="Your next move starts with understanding." intro="Explore with a sample business or practice in Simulator. Review each step and stay in control of important decisions."><div className="grid gap-5 md:grid-cols-2"><Card><h2 className="type-section">Start a sample migration</h2><p className="mt-3 leading-7 text-secondary">Meet Harbor Light Books, a synthetic business. Discover its books and follow the migration journey step by step.</p><Link className={`button mt-6${view ? " secondary" : ""}`} href={sampleEntry}>Start a sample migration</Link><p className="mt-3 text-sm text-muted">Your migration starts when you choose to begin discovery.</p></Card><Card><h2 className="type-section">Practice with context</h2><p className="mt-3 leading-7 text-secondary">Rehearse with the Harbor Light sample and learn what a successful move looks like.</p><Link className="button secondary mt-6" href="/simulator">Practice in Simulator</Link></Card></div>
    <section><h2 className="type-section">How would you like to experience MoveBooks AI?</h2><Card className="mt-4"><h3 className="type-card">Try your data</h3><p className="mt-3">Check a de-identified test export in the local evaluation version. Uploads are unavailable in this public Beta; no real accounting system is changed.</p><Link className="button secondary mt-4" href="/try-your-data">Try Your Data</Link></Card></section><section aria-label="Selected migration"><h2 className="type-section">Your migration</h2>{loading ? <p role="status" className="mt-4">Finding your selected migration…</p> : error ? <Alert tone="warning" title="Migration unavailable"><p>{error}</p></Alert> : view ? <div className="card mt-4 p-5"><p className="break-words">{phases[view.phase].name} · {view.status.replaceAll("_", " ")}</p><Link className="button mt-4" href={`${phases[view.phase].route}?session=${view.id}`}>Continue My Migration</Link><Link className="button secondary mt-4 ml-2" href={`/trust?session=${view.id}`}>View evidence</Link></div> : <p className="mt-4 text-secondary">No migration selected in this browser. Explore a sample to begin.</p>}<Button variant="ghost" className="mt-3" onClick={refresh} disabled={loading}>Refresh migration</Button></section>
    <section><h2 className="type-section">Your five-phase guide</h2><ol className="mt-5 grid gap-4 md:grid-cols-5">{phases.map(phase => <li id={phase.name.toLowerCase()} key={phase.name} className="card scroll-mt-8 p-5"><h3 className="font-bold">{phase.name}</h3><p className="mt-2 text-sm text-secondary">{phase.detail}</p><p className="mt-3 text-sm">{phase.copy}</p><Link className="mt-4 inline-block font-semibold text-primary underline" href={`/learn#${phase.topic}`}>Learn about {phase.name}</Link></li>)}</ol></section><p className="text-sm text-muted">Real accounting-provider connections are not available. <Link className="underline" href="/trust#beta-limitations">See Beta limitations</Link>.</p></Surface>;
}
