"use client";
import Link from "next/link";
import { Alert, Badge, Button, Card } from "@/components/ui";
import { Surface } from "./Surface";
import { phases } from "./content";
import { type TraceRow, useSessionView } from "./session";
function Trace({ title, rows }: { title: string; rows: TraceRow[] }) {
  return <section><h2 className="type-section">{title}</h2><p className="mt-2 text-sm text-muted">{rows.length ? `Latest ${Math.min(30, rows.length)} of ${rows.length} records in this snapshot.` : "No evidence recorded for this section yet. Absence is not a passed check."}</p><ol className="mt-4 space-y-3">{rows.slice(-30).reverse().map((row, index) => <li key={`${row.id}-${index}`} className="card break-words p-5"><Badge>{row.kind}</Badge><h3 className="mt-3 font-semibold">{row.title}</h3><p className="mt-2 text-sm">Status: {row.status} · {row.actor}</p>{row.time && <p className="mt-2 text-sm text-muted"><time dateTime={row.time}>{row.time}</time></p>}{row.tool && <p className="mt-2 text-sm">Tool: {row.tool}</p>}<details className="mt-3"><summary className="cursor-pointer py-2 font-semibold text-primary">Evidence and audit reference</summary><p className="mt-2 text-xs">Audit: {row.id || "Not recorded"}</p><ul className="mt-2 space-y-1 text-sm">{row.evidence.map((ref, i) => <li key={i}>{ref}</li>)}</ul>{!row.evidence.length && <p className="text-sm text-muted">No additional evidence references supplied.</p>}</details></li>)}</ol></section>;
}
export function Trust() {
  const { view, loading, error, refresh } = useSessionView();
  return <Surface sourceScope="Sample or user-provided source · synthetic target" eyebrow="Trust / Agent Operations" title="See what happened. Understand why." intro="Payload-free summaries of the selected local session. Recommendations, verified checks and human decisions are different kinds of evidence."><div className="grid gap-4 md:grid-cols-3">{[["AI recommendation", "A suggestion to review, not authorization. Deterministic fallback is the default. Explicitly configured synthetic dev/test guidance may use Gemini; its source and fallback state are labeled in the workflow."], ["Deterministic verification", "Versioned rules check financial facts. A recommendation or approval cannot override a failed check."], ["Human decision", "An attributable decision with time and evidence. Consequential changes stay under human control."]].map(([title, body]) => <Card key={title}><h2 className="type-card">{title}</h2><p className="mt-3 leading-7 text-secondary">{body}</p></Card>)}</div>
    <section id="beta-limitations" className="scroll-mt-8"><h2 className="type-section">Beta limitations</h2><p className="mt-3 text-secondary">This is a bounded synthetic Beta, not a production or compliance-ready service. Do not use production customer data. Real accounting-provider connections are not available.</p><details className="mt-4"><summary className="cursor-pointer py-2 font-semibold text-primary">Sign-in, saved progress and data limits</summary><ul className="mt-3 list-disc space-y-2 pl-5 text-secondary"><li>Google sign-in identifies your account. The API verifies that account and its access to each migration; approval identity is checked on the server.</li><li>Cloud synthetic migrations use durable storage. Local demo sessions may expire on restart.</li><li>Try Your Data accepts controlled, de-identified test exports only in the local evaluation version. Public-Beta cloud uploads remain disabled; target operations remain synthetic.</li><li>Financial checks and workflow controls remain deterministic. AI guidance cannot approve consequential decisions for you.</li></ul></details></section>
    <div><Button onClick={refresh} disabled={loading}>Refresh evidence</Button><p className="mt-3 text-sm text-muted">Snapshot only, not live monitoring. Private reasoning, raw prompts and financial payloads are not displayed.</p></div>
    {loading ? <p role="status">Reading session evidence…</p> : error ? <Alert tone="warning" title="Evidence unavailable"><p>{error}</p><Link className="underline" href="/product">Open Product</Link></Alert> : !view ? <Alert tone="info" title="No session selected"><p>Start the sample business, then return here to inspect its actual evidence.</p><Link className="button secondary mt-3" href="/product">Open Product</Link></Alert> : <>
      <section className="panel break-words p-6"><h2 className="type-section">Current journey stage: {phases[view.phase].name}</h2><p className="mt-3">{view.sourceKind}</p><p className="mt-3">Workflow status: {view.status.replaceAll("_", " ")}</p><p className="mt-2 text-sm">Session: {view.id}</p><Link className="button mt-5" href={`${phases[view.phase].route}?session=${view.id}`}>Return to governed workflow</Link><Link className="button secondary mt-5 ml-2" href={`/support?session=${view.id}&stage=${view.phase}`}>Get contextual help</Link></section>
      <section><h2 className="type-section">Blockers and decisions needing attention</h2>{view.blockers.length ? <ul className="mt-4 space-y-3">{view.blockers.map((blocker, i) => <li key={i}><Alert tone="warning" title="Review in workflow"><p>{blocker}</p></Alert></li>)}</ul> : <p className="mt-3 text-secondary">No blockers in the displayed evidence. This is not a readiness or completion determination; the workflow remains authoritative.</p>}</section>
      <div className="grid items-start gap-8 lg:grid-cols-2"><Trace title="Agent activity and tools" rows={view.activity}/><Trace title="Human approvals and decisions" rows={view.decisions}/><Trace title="Deterministic checks" rows={view.checks}/><Trace title="Lifecycle audit" rows={view.events}/></div></>}
  </Surface>;
}
