"use client";
import Link from "next/link";
import { Alert, Badge, Button } from "@/components/ui";
import { IdentityEntry } from "@/components/IdentityEntry";
import { useIdentity } from "@/components/IdentityProvider";
import { cloudIdentity } from "@/lib/identity";
import { Surface } from "./Surface";
import { AnchoredDetails } from "./AnchoredDetails";
import { phases } from "./content";
import { isSessionId, type TraceRow, useSessionView } from "./session";
function Trace({ title, rows }: { title: string; rows: TraceRow[] }) {
  return <section><h2 className="type-section">{title}</h2><p className="mt-2 text-sm text-muted">{rows.length ? `Latest ${Math.min(30, rows.length)} of ${rows.length} records in this snapshot.` : "No evidence recorded for this section yet. Absence is not a passed check."}</p><ol className="mt-4 space-y-3">{rows.slice(-30).reverse().map((row, index) => <li key={`${row.id}-${index}`} className="card break-words p-5"><Badge>{row.kind}</Badge><h3 className="mt-3 font-semibold">{row.title}</h3><p className="mt-2 text-sm">Status: {row.status} · {row.actor}</p>{row.time && <p className="mt-2 text-sm text-muted"><time dateTime={row.time}>{row.time}</time></p>}{row.tool && <p className="mt-2 text-sm">Tool: {row.tool}</p>}<details className="mt-3"><summary className="cursor-pointer py-2 font-semibold text-primary">Evidence and audit reference</summary><p className="mt-2 text-xs">Audit: {row.id || "Not recorded"}</p><ul className="mt-2 space-y-1 text-sm">{row.evidence.map((ref, i) => <li key={i}>{ref}</li>)}</ul>{!row.evidence.length && <p className="text-sm text-muted">No additional evidence references supplied.</p>}</details></li>)}</ol></section>;
}

export function Trust({ evidenceMode = false, session }: { evidenceMode?: boolean; session?: string }) {
  // Plain public Trust never mounts a session reader, including with a saved selection.
  if (evidenceMode) return cloudIdentity() ? <CloudEvidence session={session}/> : <Evidence/>;
  return <Surface compact eyebrow="Trust" title="A move you can inspect." intro="Agents coordinate, deterministic rules verify financial facts, and people approve consequential decisions." action={<Link className="button" href="/workspace">Try the Beta</Link>}>
    <ul className="trust-principles"><li><strong>People approve:</strong> consequential decisions are explicit and attributable.</li><li><strong>Rules verify:</strong> failed financial checks block progress.</li><li><strong>Workspaces are owned:</strong> the API verifies identity and access.</li><li><strong>AI is advisory:</strong> labeled fallback preserves the same controls.</li></ul>
    <AnchoredDetails id="financial-controls" title="Financial controls and human approvals"><p>Versioned rules check counts, balances and relationships. The same inputs and rule versions produce the same financial result. An AI recommendation or human approval cannot waive a failed check.</p><p>People approve mappings, plan consent, bounded recovery, consequential settings, onboarding and first-task decisions. Decisions retain actor, time and evidence. Agents coordinate permitted discovery, batches and retries; they cannot approve their own proposals.</p></AnchoredDetails>
    <AnchoredDetails id="workspace-access" title="Identity, saved progress and evidence"><p>Google sign-in identifies your account; the API checks ownership and approval identity. Cloud synthetic workspaces and checkpoints persist. Local demo sessions may expire when the API restarts.</p><p>Open Trust &amp; Evidence from your migration task to inspect its authorized snapshot. Public Trust does not read a stored migration pointer. Empty evidence is not a passed check; refresh reads a snapshot, not live monitoring. Raw financial payloads, prompts and hidden reasoning are excluded.</p><Link className="public-text-link" href="/guide#trust">How to inspect migration evidence</Link></AnchoredDetails>
    <AnchoredDetails id="ai-boundaries" title="AI limitations and fallback"><p>AI predicts or explains mappings and remedies with uncertainty; confidence is not a guarantee or permission. Deterministic-only guidance is the public Beta default. Optional configured synthetic dev/test Gemini guidance labels its source and fallback. Google Cloud, Gemini and Google ADK describe the stack, not a live model call on every interaction; managed ADK remains disabled.</p><p>Optional Gemini receives a bounded repository-sample summary: plan stages, mapping concepts and candidates, failure classes, proposal states and onboarding checklist states. Uploaded exports, raw financial rows and amounts, actor identities, comments and credentials are excluded. Advice cannot approve, migrate, retry, post an invoice or declare Business Ready · Verified. Unavailable or invalid advice falls back within the same controls.</p><Link className="public-text-link" href="/learn#confidence">What confidence means</Link></AnchoredDetails>
    <AnchoredDetails id="beta-limitations" title="Beta limitations"><p>This is a bounded synthetic Beta, not a production or compliance-ready service. Business records, source/target operations and invoice posting stay synthetic. Real accounting-provider connections are unavailable.</p><p>Do not use real customer or production provider data, names, financial records, account or tax numbers, passwords or tokens. Cloud test-export uploads remain disabled, including for signed-in users. Only local evaluation accepts controlled synthetic or de-identified exports.</p><p>No production uptime or staffed-support commitment. This is not accounting, tax or legal advice. MoveBooks AI is independent and provider-neutral, with no accounting-provider affiliation.</p><Link className="public-text-link" href="/try-your-data">Local evaluation availability</Link></AnchoredDetails>
  </Surface>;
}
function CloudEvidence({ session }: { session?: string }) {
  const { identity } = useIdentity();
  const linked = session ?? null;
  if (linked !== null && !isSessionId(linked)) return <Surface compact eyebrow="Evidence" title="Evidence unavailable." intro="This migration reference is invalid."><p role="alert">Invalid session reference. No replacement migration was created.</p><Link className="public-text-link" href="/trust">Public trust principles</Link></Surface>;
  if (!identity) return <Surface compact eyebrow="Evidence" title="Sign in to inspect your migration." intro="Evidence belongs to an owner-protected synthetic workspace."><IdentityEntry destination={`/trust?view=evidence${linked ? `&session=${linked}` : ""}`}/><Link className="public-text-link" href="/trust">Public trust principles</Link></Surface>;
  return <Evidence/>;
}
function Evidence() {
  const { view, loading, error, refresh } = useSessionView();
  return <Surface compact sourceScope="Migration evidence · synthetic target" eyebrow="Evidence & Results" title="Review what happened." intro="Read the authorized snapshot; decisions and exact financial terms remain in their original tasks.">
    <div><Button variant={view ? "secondary" : "primary"} onClick={refresh} disabled={loading}>Refresh evidence</Button><p className="mt-2 text-secondary">Snapshot only. No private reasoning, raw prompts or financial payloads.</p></div>
    {loading ? <p role="status">Reading session evidence…</p> : error ? <Alert tone="warning" title="Evidence unavailable"><p>{error}</p><Link className="underline" href="/workspace">Open My Migration</Link></Alert> : !view ? <Alert tone="info" title="No session selected"><p>Open an owned migration reference to inspect its actual evidence. No replacement migration was created.</p><Link className="public-text-link mt-3" href="/workspace">Open My Migration</Link></Alert> : <>
      <section className="panel break-words p-6"><h2 className="type-section">Current journey stage: {phases[view.phase].name}</h2><p className="mt-3">{view.sourceKind}</p><p className="mt-3">Workflow status: {view.status.replaceAll("_", " ")}</p><p className="mt-2 text-sm">Session: {view.id}</p><Link className="button mt-5" href={`${phases[view.phase].route}?session=${view.id}`}>Return to migration</Link><Link className="button secondary mt-5 ml-2" href={`/support?session=${view.id}&stage=${view.phase}`}>Get contextual help</Link></section>
      <section><h2 className="type-section">Blockers and decisions needing attention</h2>{view.blockers.length ? <ul className="mt-4 space-y-3">{view.attention.map((item, i) => <li key={i}><Alert tone="warning" title={item.title}><p className="text-sm">Evidence: {item.evidence}</p></Alert></li>)}</ul> : <p className="mt-3 text-secondary">No blockers in the displayed evidence. This is not a readiness or completion determination; the workflow remains authoritative.</p>}</section>
      <div className="grid items-start gap-8 lg:grid-cols-2"><Trace title="Agent activity and tools" rows={view.activity}/><Trace title="Human approvals and decisions" rows={view.decisions}/><Trace title="Deterministic checks" rows={view.checks}/><Trace title="Lifecycle audit" rows={view.events}/></div></>}

    <Link className="public-text-link" href="/trust">Public trust principles and Beta boundaries</Link>
  </Surface>;
}
