import Link from "next/link";
import { ArrowRight, Cloud, Eye, Network, ShieldCheck, TrendingUp } from "lucide-react";
import { Badge, Card } from "@/components/ui";
import { phases, publicLinks } from "@/components/public-surfaces/content";
import { ProductVision } from "@/components/public-surfaces/ProductVision";
const reasons = [{ Icon: TrendingUp, title: "Scale", copy: "Support growth without adding manual work." }, { Icon: Cloud, title: "Access", copy: "Work securely from anywhere." }, { Icon: Network, title: "Connect", copy: "Reduce disconnected tools and duplicate processes." }, { Icon: Eye, title: "See clearly", copy: "Improve reporting and operational visibility." }];
export default function Home() {
  return <main id="main-content">
    <section className="shell grid items-center gap-12 py-16 sm:py-24 lg:grid-cols-[1.2fr_1fr]">
      <div><Badge>MoveBooks AI Beta</Badge><h1 className="serif mt-5 text-5xl leading-tight tracking-tight sm:text-7xl">Move your books.<br/><span className="text-primary">Keep your confidence.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-secondary">Explore the migration journey safely using synthetic data. Prepare your books, review important decisions, and check the results.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/product" className="button">Explore MoveBooks <ArrowRight size={18} aria-hidden="true"/></Link><Link href="#how-it-works" className="button secondary">See how it works</Link></div><p className="mt-5 max-w-xl text-sm text-muted">Bounded synthetic Beta · No production customer data · <Link className="underline" href="/trust#beta-limitations">Beta limitations</Link></p></div>
      <section className="panel p-6 sm:p-8" aria-label="Journey overview, not live progress"><p className="text-sm font-semibold text-primary">From migration uncertainty to business-ready accounting</p><ol className="mt-6 space-y-5">{phases.map((phase, index) => <li key={phase.name} className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-token font-bold text-primary">{index + 1}</span><div><h2 className="font-bold">{phase.name}</h2><p className="mt-1 text-sm text-secondary">{phase.copy}</p></div></li>)}</ol><div className="mt-7 border-t border-token pt-5"><p className="flex items-center gap-2 font-bold"><ShieldCheck aria-hidden="true" size={20}/> Outcome: Business Ready · Verified</p><p className="mt-2 text-xs text-muted">Verified First Productive Use, demonstrated with a synthetic business.</p></div></section>
    </section>
    <ProductVision/>
    <section className="shell py-12" aria-labelledby="why-migrate"><h2 id="why-migrate" className="type-page mt-3">Why businesses migrate</h2><p className="mt-4 max-w-3xl text-secondary">Outgrown systems, fragmented data, manual processes and limited visibility can make everyday accounting harder to operate and scale.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{reasons.map(({ Icon, title, copy }) => <Card key={title}><Icon className="text-primary" aria-hidden="true" size={24}/><h3 className="mt-6 font-bold">{title}</h3><p className="mt-2 leading-7 text-secondary">{copy}</p></Card>)}</div></section>
    <section className="dark-section my-12 py-16"><div className="shell"><h2 className="type-page">The questions behind every move</h2><div className="mt-6 grid gap-6 md:grid-cols-3">{[
      ["Will all my data move correctly?", "Customers, vendors, accounts, transactions and configuration need to arrive complete and usable."],
      ["Will my numbers still be right?", "Balances, totals and reconciliation must match before migration is considered successful."],
      ["Will my business be ready to operate?", "Configuration, access and onboarding must work before the migration is truly complete."],
    ].map(([question, context]) => <div key={question}><h3 className="type-section">{question}</h3><p className="mt-4 leading-7 text-secondary">{context}</p></div>)}</div><p className="mt-8 max-w-3xl text-xl leading-8">Migration is more than moving files. It is a financial-trust and business-readiness problem.</p></div></section>
    <section id="how-it-works" className="shell scroll-mt-8 py-12" aria-labelledby="how-heading"><h2 id="how-heading" className="type-page">How MoveBooks works</h2><div className="mt-8 grid gap-4 md:grid-cols-5">{phases.map(phase => <Card key={phase.name}><h3 className="font-bold text-primary">{phase.name}</h3><p className="mt-3 text-sm font-semibold">{phase.detail}</p><p className="mt-3 text-sm leading-6 text-secondary">{phase.copy}</p></Card>)}</div></section>
    <section className="shell py-12"><h2 className="type-page">Trust by design</h2><p className="mt-4 max-w-3xl text-xl leading-8 text-secondary">AI that assists. Rules that verify. People who decide.</p><div className="mt-8 grid gap-5 md:grid-cols-3">{[["Evidence before action", "See the facts behind a recommendation, the limits of confidence and what still needs attention."],["You approve key decisions", "Agents coordinate work. People govern consequential changes. A blocked check cannot be approved away."],["We verify your numbers", "Rules check counts, balances and relationships. Success needs evidence—not a convincing explanation."]].map(([title, copy]) => <Card key={title}><h3 className="type-card">{title}</h3><p className="mt-3 leading-7 text-secondary">{copy}</p></Card>)}</div><p className="mt-6 text-sm text-muted">Built with Google Cloud, Gemini and Google ADK</p></section>
    <section className="shell py-12"><div className="panel grid gap-8 p-8 md:grid-cols-2"><div><p className="eyebrow text-primary">Available in this Beta</p><h2 className="type-section mt-3">A complete synthetic journey.</h2><p className="mt-4 leading-7 text-secondary">Discover Harbor Light Books, approve mappings, recover from a controlled failure, verify the result, configure the business, and complete onboarding and a verified synthetic invoice.</p><Link className="button mt-6" href="/product">Start a sample migration</Link></div><div><h3 className="font-bold">Deployment boundaries</h3><p className="mt-3 leading-7 text-secondary">Cloud uploads, live provider connections and managed ADK remain unavailable. Live Gemini advice requires explicit deployment configuration and is disabled by default. Production customer deployment and live support operations are not available.</p><p className="mt-4 text-sm text-muted">Independent and provider-neutral. No affiliation with or representation of any accounting software provider.</p></div></div><nav aria-label="Explore MoveBooks AI" className="mt-8 flex flex-wrap gap-4">{publicLinks.map(([label, href]) => <Link key={href} className="button secondary small" href={href}>{label}</Link>)}</nav></section>
  </main>;
}
