import Link from "next/link";
import { ArrowRight, Cloud, Eye, Network, ShieldCheck, TrendingUp } from "lucide-react";
import { Badge, Card } from "@/components/ui";
import { phases, publicLinks, scope } from "@/components/public-surfaces/content";
const reasons = [{ Icon: TrendingUp, title: "Scale", copy: "Support business growth" }, { Icon: Cloud, title: "Access", copy: "Cloud access and collaboration" }, { Icon: Network, title: "Connect", copy: "Integrations and automation" }, { Icon: Eye, title: "See & Act", copy: "Better visibility, reporting and modern AI-enabled workflows" }];
export default function Home() {
  return <main id="main-content">
    <section className="shell grid items-center gap-12 py-16 sm:py-24 lg:grid-cols-[1.2fr_1fr]">
      <div><Badge>Synthetic public-reference Beta</Badge><p className="eyebrow mt-7 text-primary">MoveBooks AI</p><h1 className="serif mt-5 text-5xl leading-tight tracking-tight sm:text-7xl">Move your books.<br/><span className="text-primary">Keep your confidence.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-secondary">Understand your accounting environment, prepare your data, migrate safely, validate the result, and get operational — with intelligent agents throughout the journey.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/product" className="button">Explore Beta <ArrowRight size={18} aria-hidden="true"/></Link><Link href="#how-it-works" className="button secondary">See How It Works</Link></div><p className="mt-5 max-w-xl text-sm text-muted">{scope}</p></div>
      <section className="panel p-6 sm:p-8" aria-label="Journey overview, not live progress"><p className="eyebrow text-primary">From Migration Uncertainty to Business-Ready Accounting</p><ol className="mt-6 space-y-5">{phases.map((phase, index) => <li key={phase.name} className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-token font-bold text-primary">{index + 1}</span><div><h2 className="font-bold uppercase tracking-wide">{phase.name}</h2><p className="mt-1 text-sm text-secondary">{phase.copy}</p></div></li>)}</ol><div className="mt-7 border-t border-token pt-5"><p className="flex items-center gap-2 font-bold"><ShieldCheck aria-hidden="true" size={20}/> Outcome: Business Ready · Verified</p><p className="mt-2 text-xs text-muted">Verified First Productive Use, demonstrated with a synthetic business.</p></div></section>
    </section>
    <section className="shell py-12" aria-labelledby="why-migrate"><p className="eyebrow text-primary">Why migrate?</p><h2 id="why-migrate" className="type-page mt-3">Make room for the way you work next.</h2><p className="mt-4 max-w-3xl text-secondary">Businesses migrate because the current operating model begins constraining growth and productivity.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{reasons.map(({ Icon, title, copy }) => <Card key={title}><Icon className="text-primary" aria-hidden="true" size={24}/><h3 className="mt-6 font-bold uppercase">{title}</h3><p className="mt-2 leading-7 text-secondary">{copy}</p></Card>)}</div></section>
    <section className="dark-section my-12 py-16"><div className="shell"><p className="eyebrow text-primary">The questions behind every move</p><div className="mt-6 grid gap-6 md:grid-cols-3">{["Will everything move?", "Will the numbers still be right?", "Will the business actually work afterward?"].map(question => <h2 key={question} className="type-section">{question}</h2>)}</div><ul aria-label="Connected migration concerns" className="mt-8 flex flex-wrap gap-3">{["Data quality", "Mappings", "Reconciliation", "Configuration", "Permissions", "Onboarding", "Recovery"].map(item => <li key={item}><Badge>{item}</Badge></li>)}</ul><p className="mt-8 max-w-3xl text-xl leading-8">Migration is not file transfer. It is a trust and operational-readiness problem.</p></div></section>
    <section id="how-it-works" className="shell scroll-mt-8 py-12" aria-labelledby="how-heading"><h2 id="how-heading" className="type-page">One journey. Five clear phases.</h2><div className="mt-8 grid gap-4 md:grid-cols-5">{phases.map(phase => <Card key={phase.name}><h3 className="font-bold uppercase text-primary">{phase.name}</h3><p className="mt-3 text-sm font-semibold">{phase.detail}</p><p className="mt-3 text-sm leading-6 text-secondary">{phase.copy}</p></Card>)}</div></section>
    <section className="shell py-12"><h2 className="type-page">Trust you can inspect.</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[["Evidence before action", "See the facts behind a recommendation, the limits of confidence and what still needs attention."],["You approve key decisions", "Agents coordinate work. People govern consequential changes. A blocked check cannot be approved away."],["We verify your numbers", "Rules check counts, balances and relationships. Success needs evidence—not a convincing explanation."]].map(([title, copy]) => <Card key={title}><h3 className="type-card">{title}</h3><p className="mt-3 leading-7 text-secondary">{copy}</p></Card>)}</div><p className="mt-6 leading-7 text-secondary">Rules verify. AI predicts. GenAI reasons. Agents orchestrate and act. Humans govern consequential decisions.</p></section>
    <section className="shell py-12"><div className="panel grid gap-8 p-8 md:grid-cols-2"><div><p className="eyebrow text-primary">Available in this Beta</p><h2 className="type-section mt-3">A complete synthetic journey.</h2><p className="mt-4 leading-7 text-secondary">Discover Harbor Light Books, approve mappings, recover from a controlled failure, verify the result, configure the business, and complete onboarding and a verified synthetic invoice.</p><Link className="button mt-6" href="/product">Explore the working Beta</Link></div><div><h3 className="font-bold">Building next, not available here</h3><p className="mt-3 leading-7 text-secondary">Your own data, live provider connections, Google identity, live Gemini and managed ADK runtime. Production customer deployment and live support operations are not available.</p><p className="mt-4 text-sm text-muted">Independent and provider-neutral. No affiliation with or representation of any accounting software provider.</p></div></div><nav aria-label="Explore MoveBooks AI" className="mt-8 flex flex-wrap gap-4">{publicLinks.map(([label, href]) => <Link key={href} className="button secondary small" href={href}>{label}</Link>)}</nav></section>
  </main>;
}
